# Generated by Django 5.0 on 2024-01-08 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="name",
            field=models.CharField(default="name...", max_length=250),
            preserve_default=False,
        ),
    ]
